version: '3'
services: 
  db: 
    container_name: chatbot_db
    image: mysql:5.7
    ports: 
      - "3306:3306"  
    environment: 
      - MYSQL_ROOT_PASSWORD=iii
    volumes: 
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d/
  jupyter-tutorial:
    image: asoo571314/jupyter-notebook:1.0
    container_name: jupyter_notebook
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8880:8888"
      - "80:5000"
    volumes:
      - ./code:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
